---
- include: redhat/install.yml
  when: ansible_os_family == 'RedHat'

- include: debian/install.yml
  when: ansible_os_family == 'Debian'

- name: ensure MySQL is running
  service:
    name: "{{ mysql_service_name }}"
    state: started
    enabled: yes
