---
- name: load the os specific variables
  include_vars: "{{ ansible_os_family | lower }}/default.yml"

- include: install.yml
- include: configure.yml
- include: secure.yml
- include: databases.yml
- include: users.yml
- include: monit.yml
  when: monit_protection is defined and monit_protection == true
