---
- name: check connection access
  shell: /usr/bin/mysqladmin -u root -p{{ mysql_root_password }} status &> /dev/null
  register: root_access
  ignore_errors: True

- name: set initial root password
  command: /usr/bin/mysqladmin -u root password '{{ mysql_root_password }}'
  register: root_new_pass
  when: root_access | failed

- name: grant root access
  mysql_user:
    login_user: root
    login_password: "{{ mysql_root_password }}"
    user: root
    host: "{{ item }}"
    password: "{{ mysql_root_password }}"
  with_items:
   - "{{ ansible_hostname }}"
   - 127.0.0.1
   - ::1
   - localhost
  when: ansible_hostname != 'localhost'

- name: grant root access
  mysql_user:
    login_user: root
    login_password: "{{ mysql_root_password }}"
    user: root
    host: "{{ item }}"
    password: "{{ mysql_root_password }}"
  with_items:
   - 127.0.0.1
   - ::1
   - localhost
  when: ansible_hostname == 'localhost'

- name: configure MySql for easy access as root user
  template:
    src: root_dot_my.cnf.j2
    dest: /root/.my.cnf
    owner: root
    group: root
    mode: 0600

- name: remove anonymous MySQL server user
  mysql_user:
    login_user: root
    login_password: "{{ mysql_root_password }}"
    name: ""
    host: "{{ item }}"
    state: absent
  with_items:
    - "{{ ansible_hostname }}"
    - localhost

- name: remove the MySQL test database
  mysql_db:
    login_user: root
    login_password: "{{ mysql_root_password }}"
    name: test
    state: absent
