# file: mysql/vars/redhat/default.yml

mysql_packages:
  - mysql
  - mysql-server
  - MySQL-python

mysql_service_name: mysqld

mysql_cnf_path: /etc/my.cnf

mysql_sock_file: /var/lib/mysql/mysql.sock
